# Generated by Django 2.2.20 on 2021-05-07 03:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=20)),
                ('map_background', models.ImageField(upload_to=app.models.report_map_background_path, verbose_name='map background')),
                ('map_sketch', models.ImageField(upload_to=app.models.report_map_sketch_path, verbose_name='map sketch')),
                ('map_composite', models.ImageField(height_field='map_height', help_text='The map background and sketch are composited together into this while saving.', upload_to=app.models.report_map_composite_path, verbose_name='map composite', width_field='map_width')),
                ('map_height', models.PositiveSmallIntegerField(default=210, null=True)),
                ('map_width', models.PositiveSmallIntegerField(default=230, null=True)),
            ],
            options={
                'verbose_name': 'field map',
                'verbose_name_plural': 'field maps',
            },
        ),
    ]
